include:
  - project: devops/cicd/templates
    ref: v0.2.2
    file: docker.gitlab-ci.yml
  - project: devops/cicd/templates
    ref: v0.2.2
    file: dotnet.gitlab-ci.yml
  - project: devops/cicd/templates
    ref: v0.2.2
    file: disable-detached.gitlab-ci.yml

variables:
  PROJECT: payment-api
  CHART_DIR: charts/payment-api
  IS_MULTI_APP: 'true'

stages:
  - init
  - build_and_test
  - publish
  - deploy

app:test:generate-config:
  stage: init
  extends: .dotnet_generate_test_config
  variables:
    TEST_BASE_IMAGE: plinfharbor.vpayusa.net/base-images/dotnet/core/sdk:2.1-bionic

app:test:
  stage: build_and_test
  needs:
    - app:test:generate-config
  trigger:
    include:
      - artifact: app-test-config.yml
        job: app:test:generate-config
    strategy: depend

helm:lint:
  stage: build_and_test
  needs: []
  trigger:
    include:
      - local: /.gitlab-ci/helm-lint.gitlab-ci.yml
    strategy: depend

build:api:
  stage: build_and_test
  extends: .docker_build
  needs: []
  variables:
    PREBUILD_COMMAND: scripts/generate_tar.sh
    IMAGE_NAME: payment-web-api
    DOCKERFILE: Dockerfile
    PROJECT_TAR: projectfiles.tar
    PROJECT_DIR: VPay.Payment.Api
    PROJECT_NAME: VPay.Payment.Api
    DOTNET_VERSION: '2.1'
    DOTNET_RUNTIME_VARIANT: bionic-db2
    BUILD_ARGS: "PROJECT_TAR PROJECT_DIR PROJECT_NAME DOTNET_VERSION DOTNET_RUNTIME_VARIANT"

publish:api:
  stage: publish
  extends: .docker_publish
  variables:
    IMAGE_NAME: payment-web-api

deploy:
  stage: deploy
  trigger:
    include:
      - local: /.gitlab-ci/deploy.gitlab-ci.yml
  rules:
    - if: $CHART_DIR && $CI_COMMIT_TAG
      when: on_success
