version: '3.5'

services:
  paymentwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDevelopment
      - ASPNETCORE_Logging__GELF__AdditionalFields__namespace=client-payments-local
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5013:80"

  vpay.payment.db2:
    environment:
      PERSISTENT_HOME: false