include:
  - project: devops/cicd/templates
    ref: v0.2.0
    file: helm.gitlab-ci.yml

# Deployment steps ran in parent pipeline instead of child pipeline to work around GitLab issue
# stages:
#   - deploy-dev
#   - deploy-stg
#   - security-gate
#   - deploy-prod

variables:
  IS_MULTI_APP: 'true'

plano-dev:
  stage: deploy-dev
  extends: .helm_deploy_pldev
  environment:
    kubernetes:
      namespace: payment-api-dev

stl-dev:
  stage: deploy-dev
  extends: .helm_deploy_stldev
  environment:
    kubernetes:
      namespace: payment-api-dev

plano-stg:
  stage: deploy-stg
  extends: .helm_deploy_plstg
  environment:
    kubernetes:
      namespace: payment-api-stage

stl-stg:
  stage: deploy-stg
  extends: .helm_deploy_stlstg
  environment:
    kubernetes:
      namespace: payment-api-stage

labdog:create-deployment:
  stage: security-gate
  extends: .labdog_create_deployment
  variables:
    PROD_DEPLOY_STAGE_NAME: deploy-prod

plano-prod:
  stage: deploy-prod
  extends: .helm_deploy_plprod
  environment:
    kubernetes:
      namespace: payment-api-prod

stl-prod:
  stage: deploy-prod
  extends: .helm_deploy_stlprod
  environment:
    kubernetes:
      namespace: payment-api-prod
