include:
  - project: devops/cicd/templates
    ref: v1.1.1
    file:
      - helm.gitlab-ci.yml

stages:
  - deploy-dev
  - deploy-stg
  - security-gate
  - deploy-prod

plano-dev:
  stage: deploy-dev
  extends: .helm_deploy_pldev
  environment:
    kubernetes:
      namespace: client-payments-dev

stl-dev:
  stage: deploy-dev
  extends: .helm_deploy_stldev
  environment:
    kubernetes:
      namespace: client-payments-dev

plano-stg:
  stage: deploy-stg
  extends: .helm_deploy_plstg
  environment:
    kubernetes:
      namespace: client-payments-stage

stl-stg:
  stage: deploy-stg
  extends: .helm_deploy_stlstg
  environment:
    kubernetes:
      namespace: client-payments-stage

labdog:create-deployment:
  stage: security-gate
  extends: .labdog_create_deployment
  variables:
    PROD_DEPLOY_STAGE_NAME: deploy-prod

plano-prod:
  stage: deploy-prod
  extends: .helm_deploy_plprod
  environment:
    kubernetes:
      namespace: client-payments-prod

stl-prod:
  stage: deploy-prod
  extends: .helm_deploy_stlprod
  environment:
    kubernetes:
      namespace: client-payments-prod
