include:
  - project: devops/cicd/templates
    ref: v1.1.1
    file:
      - helm.gitlab-ci.yml

stages:
  - test
  - dryrun

helm:template:
  stage: test
  extends: .helm_template

helm:lint:
  stage: test
  extends: .helm_lint

helm:lint-dev-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-dev-plano.yaml

helm:lint-dev-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-dev-stl.yaml

helm:lint-stg-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-plano.yaml

helm:lint-stg-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-stl.yaml

helm:lint-prod-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-plano.yaml

helm:lint-prod-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-stl.yaml

dryrun:dev-pl:
  extends: .helm_dryrun_pldev
  needs:
    - helm:lint-dev-pl
  environment:
    kubernetes:
      namespace: client-payments-dev

dryrun:dev-stl:
  extends: .helm_dryrun_stldev
  needs:
    - helm:lint-dev-stl
  environment:
    kubernetes:
      namespace: client-payments-dev

dryrun:stg-pl:
  extends: .helm_dryrun_plstg
  needs:
    - helm:lint-stg-pl
  environment:
    kubernetes:
      namespace: client-payments-stage

dryrun:stg-stl:
  extends: .helm_dryrun_stlstg
  needs:
    - helm:lint-stg-stl
  environment:
    kubernetes:
      namespace: client-payments-stage

dryrun:prod-pl:
  extends: .helm_dryrun_plprod
  needs:
    - helm:lint-prod-pl
  environment:
    kubernetes:
      namespace: client-payments-prod

dryrun:prod-stl:
  extends: .helm_dryrun_stlprod
  needs:
    - helm:lint-prod-stl
  environment:
    kubernetes:
      namespace: client-payments-prod
