include:
  - project: devops/cicd/templates
    ref: v0.2.0
    file: helm.gitlab-ci.yml

stages:
  - test
  # Dryrun jobs skipped temporarily to work around GitLab issue - https://gitlab.com/gitlab-org/gitlab/-/issues/207226
  # - dryrun

variables:
  IS_MULTI_APP: 'true'

helm:template:
  stage: test
  extends: .helm_template

helm:lint:
  stage: test
  extends: .helm_lint

helm:lint-dev-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-dev-plano.yaml

helm:lint-dev-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-dev-stl.yaml

helm:lint-stg-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-plano.yaml

helm:lint-stg-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-stl.yaml

helm:lint-prod-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-plano.yaml

helm:lint-prod-stl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-stl.yaml

# Dryrun jobs skipped temporarily to work around GitLab issue - https://gitlab.com/gitlab-org/gitlab/-/issues/207226

# dryrun:dev-pl:
#   extends: .helm_dryrun_pldev
#   needs:
#     - helm:lint-dev
#   environment:
#     kubernetes:
#       namespace: payment-api-dev

# dryrun:dev-stl:
#   extends: .helm_dryrun_stldev
#   needs:
#     - helm:lint-dev
#   environment:
#     kubernetes:
#       namespace: payment-api-dev

# dryrun:stg-pl:
#   extends: .helm_dryrun_plstg
#   needs:
#     - helm:lint-stg-pl
#   environment:
#     kubernetes:
#       namespace: payment-api-stage

# dryrun:stg-stl:
#   extends: .helm_dryrun_asstg
#   needs:
#     - helm:lint-stg-stl
#   environment:
#     kubernetes:
#       namespace: payment-api-stage

# Deliberately excluding prod from dryrun
