include:
  - project: devops/cicd/templates
    ref: v0.0.5
    file: helm.gitlab-ci.yml

stages:
  - test
  - dryrun

variables:
  IS_MULTI_APP: 'true'

helm:template:
  stage: test
  extends: .helm_template

helm:lint:
  stage: test
  extends: .helm_lint

helm:lint-dev:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-dev.yaml

helm:lint-qa:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-qa.yaml

helm:lint-stg-as:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-austin.yaml

helm:lint-stg-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-stage-plano.yaml

helm:lint-prod-as:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-austin.yaml

helm:lint-prod-pl:
  stage: test
  extends: .helm_lint
  variables:
    VALUE_FILES: values-prod-plano.yaml

dryrun:dev:
  extends: .helm_dryrun_dev
  needs:
    - helm:lint-dev
  environment:
    kubernetes:
      namespace: payment-api-dev

dryrun:qa:
  extends: .helm_dryrun_qa
  needs:
    - helm:lint-qa
  environment:
    kubernetes:
      namespace: payment-api-qa

dryrun:stg-as:
  extends: .helm_dryrun_asstg
  needs:
    - helm:lint-stg-as
  environment:
    kubernetes:
      namespace: payment-api-stage

dryrun:stg-pl:
  extends: .helm_dryrun_plstg
  needs:
    - helm:lint-stg-pl
  environment:
    kubernetes:
      namespace: payment-api-stage

# Deliberately excluding prod from dryrun
