<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="VPay.Data.Db2.Abstractions" Version="1.12.2" />
    <PackageReference Include="FaxManagement.Client" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VPay.Payment.Common\VPay.Payment.Common.csproj" />
  </ItemGroup>

</Project>
