apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: client-payments-stage
  labels:
    app: payment-api-api-staging
    app.kubernetes.io/cluster-domain: stage.pks.vpayusa.net
    app.kubernetes.io/instance: payment-api-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/part-of: payment-api
    helm.sh/chart: payment-api-0.0.1
spec:
  type: ClusterIP
  selector:
    app: payment-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
