swagger: '2.0'
info:
  version: 1.0.0
  title: Trading Post Service Docs
  x-ibm-name: TradingPostServiceDocs
paths:
  /wsdl:
    get:
      tags:
        - TradingPost
      operationId: ApiTradingPostWsdlGet
      consumes: []
      parameters:
        - name: url
          in: query
          required: false
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          schema:
            type: string
        '404':
          description: Not Found
      produces:
        - text/xml
x-ibm-configuration:
  assembly:
    execute:
      - gatewayscript:
          title: gatewayscript
          version: 1.0.0
          source: |-
            var path = apim.getvariable('request.path').toLowerCase();
            var basePath = '/' + apim.getvariable('api.root').toLowerCase();
            var newPath = path.replace(basePath, '');
            apim.setvariable('new-request-path', newPath);
      - proxy:
          title: proxy
          timeout: 60
          verb: GET
          cache-response: protocol
          cache-ttl: 900
          version: 1.0.0
          target-url: $(api.properties.api-endpoint)$(new-request-path)
          description: ''
    catch: []
  gateway: datapower-gateway
  properties:
    api-endpoint:
      value: 'http://172.17.0.1:5013/api/TradingPost'
      description: ''
      encoded: false
  catalogs:
    Internal Sandbox:
      properties:
        api-endpoint: 'http://hqdevlds01.vpayusa.net:5003/api/TradingPost'
    Internal Stage:
      properties:
        api-endpoint: 'https://stg-payapi.vpayusa.net/api/TradingPost'
    Internal Prod:
      properties:
        api-endpoint: 'https://payapi.vpayusa.net/api/TradingPost'
    Stage:
      properties:
        api-endpoint: 'https://stg-payapi.vpayusa.net/api/TradingPost'
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
host: $(catalog.host)
basePath: /tradingpostdocs
schemes:
  - https
consumes:
  - application/json
produces:
  - text/xml
