apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-api-appsettings-json
  namespace: client-payments-dev
  labels:
    app: payment-api-api-development
    app.kubernetes.io/cluster-domain: dev.pks.vpayusa.net
    app.kubernetes.io/instance: payment-api-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/part-of: payment-api
    helm.sh/chart: payment-api-0.0.1
data:
  appsettings.json: '{"Logging":{"IncludeScopes":false,"Debug":{"LogLevel":{"Default":"Warning"}},"Console":{"LogLevel":{"Default":"Information"}},"GELF":{"Host":"graylogsandbox.vpayusa.net","Port":5555,"LogSource":"VPay.Payment.Api","LogLevel":{"Default":"Warning","Microsoft.AspNetCore.DataProtection":"Error"}}},"PaymentSettings":{"ValidateIP":false,"TradingPostIp":"127.0.0.1"},"Db2":{"Dsn":"AS400","Hostname":"vpay.payment.db2","Username":"db2inst1","Password":"apassword","DefaultLibraries":",VPAYPGM,VPAYFAX,VPAYBRDDTA","IsLocal":"true"},"HealthcheckSetting":{"ApplyDB2HealthCheck":true},"Db2_OBSOLETE":{"Dsn":"AS400","Hostname":"sesidev01.vpayusa.net","Username":"WSPAYAPI","Password":"yOEFgzf1DZ","DefaultLibraries":",SEWCPS,VPAYDTA,VPAYPGM,VPAYFAX,VPAYSEC,SEWVPAY,SEWACH,SEWBAS,ADMPGM,SEWADM,SEWSEC,SESEC,VPAYBRDPGM,VPAYBRDDTA,QGPL,CRYPTO,PORT835DTA,PORT835PGM,RAMNGSPEED,GUARDRCPGM,GUARDRCDTA"},"FaxmanApi":{"BaseAddress":"http://localhost:42332"}}'
  appsettings.development.json: '{"Logging":{"IncludeScopes":false,"Debug":{"LogLevel":{"Default":"Information"}},"Console":{"LogLevel":{"Default":"Information","Microsoft":"Warning"}},"LogLevel":{"Default":"Debug"},"GELF":{"LogLevel":{"Default":"Information","Microsoft":"Warning","VPay.Payment.Api.Auth.VPayAuthenticationHandler":"Information"}}},"PaymentSettings":{"ValidateIP":false,"UseCheckEmail":true,"TradingPostIp":"127.0.0.1"},"Db2":{"Dsn":"AS400","Hostname":"sesidev01.vpayusa.net","IsLocal":false},"FaxmanApi":{"BaseAddress":"https://faxman-api.dev.pks.vpayusa.net/"}}'
