apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-api-appsettings-secure-json
  namespace: client-payments-dev
  labels:
    app: payment-api-api-development
    app.kubernetes.io/cluster-domain: dev.pks.vpayusa.net
    app.kubernetes.io/instance: payment-api-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: payment-api
    app.kubernetes.io/part-of: payment-api
    helm.sh/chart: payment-api-0.0.1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store-dba
    kind: ClusterSecretStore
  target:
    name: payment-api-appsettings-secure-json
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        appsettings.secure.json: |-
          {
            "Db2": {
              "Username": "{{ .Db2Username }}",
              "Password": "{{ .Db2Password }}"
            }
          }
  data:
    - secretKey: Db2Username
      remoteRef:
        key: secret/client-payments/payment-api/dev/db2
        property: username
    - secretKey: Db2Password
      remoteRef:
        key: secret/client-payments/payment-api/dev/db2
        property: password
