apiVersion: v2
name: payment-api
description: Payment API
icon: https://www.vpayusa.com/wp-content/themes/vpay/images/logo.svg
version: 0.0.1
dependencies:
  - name: helm-gen
    version: v1.2.1
    repository: https://repo1.uhc.com/artifactory/UHG-Releases/com/uhg/optum/financials/payments/helm
