api:
  secrets:
    appsettings.secure.json:
      data:
        Db2:
          Username: '{{ vault "secret/client-payments/payment-api/${DEPLOYMENT}/db2" "username" }}'
          Password: '{{ vault "secret/client-payments/payment-api/${DEPLOYMENT}/db2" "password" }}'
  additionalConfigMaps:
    - name: vpay-custom-ca
      data:
        vpay-root-ca.crt: |
          {{ vault "devops/infra/vpay-root-ca" "certificate" }}