global:
  parent: 'payment'
api:
  environment:
    ingress:
      domains:
        - dev-payapi.vpayusa.net
  replicas: 1
  enabled: true
  generate:
    custom_configmap: true
  configMaps:
    appsettings.json:
      mount: true
      type: json
      mountPath: /app/appsettings.json
      subPath: appsettings.json
      sourceFile: VPay.Payment.Api/appsettings.json
      data: {}
    appsettings.development.json:
      mount: true
      type: json
      mountPath: /app/appsettings.Development.json
      subPath: appsettings.development.json
      sourceFile: VPay.Payment.Api/appsettings.Development.json
      data: {}
