global:
  environment:
    name: Production
    ingress:
      subdomain: prod.pks.vpayusa.net
      altSubdomains:
        - plpksprod.vpayusa.net
        - plprod.pks.vpayusa.net

api:
  replicas: 3
