chart:
  virtual:
    shared:
      image:
        registry: stlinfharbor.vpayusa.net

global:
  environment:
    name: Production
    ingress:
      subdomain: prod.pks.vpayusa.net
      altSubdomains:
        - stlpksprod.vpayusa.net

api:
  replicas: 3
  environment:
    ingress:
      domains:
        - payapi.vpayusa.net
