global:
  environment:
    name: Production
    ingress:
      subdomain: prod.pks.vpayusa.net
      altSubdomains:
        - plpksprod.vpayusa.net

api:
  replicas: 3
  environment:
    ingress:
      domains:
        - payapi.vpayusa.net

