global:
  environment:
    name: Staging
    ingress:
      subdomain: stg.pks.vpayusa.net
      altSubdomains:
        - plpksstg.vpayusa.net

api:
  environment:
    ingress:
      domains:
        - stg-payapi.vpayusa.net
