chart:
  virtual:
    shared:
      image:
        registry: stlinfharbor.vpayusa.net

global:
  environment:
    name: Staging
    ingress:
      subdomain: stg.pks.vpayusa.net
      altSubdomains:
        - stlpksstg.vpayusa.net

api:
  environment:
    ingress:
      domains:
        - stg-payapi.vpayusa.net
