chart:
  virtual:
    shared:
      image:
        registry: centraluhg.jfrog.io
        tag: latest
        pullPolicy: Always
      env:
        ASPNETCORE_ENVIRONMENT: '{{ .Values.global.environment.name }}'
        DOTNET_ENVIRONMENT: '{{ .Values.global.environment.name }}'
        ASPNETCORE_Logging__GELF__AdditionalFields__environment: '{{ .Values.global.environment.name }}'
        ASPNETCORE_Logging__GELF__AdditionalFields__namespace: '{{ .Release.Namespace }}'
        DOTNET_Logging__GELF__AdditionalFields__environment: '{{ .Values.global.environment.name }}'
        DOTNET_Logging__GELF__AdditionalFields__namespace: '{{ .Release.Namespace }}'
      generate:
        deployment: true
        service: true
        ingress: true
        secret: true
        configmap: true
      extraVolumeMounts:
        - mountPath: /usr/local/share/ca-certificates/vpay-root-ca.crt
          name: vpay-custom-ca-generation
          subPath: vpay-root-ca.crt
        - mountPath: /etc/ssl/certs
          name: common-cert
      initContainers:
        - name: install-ca
          image: centraluhg.jfrog.io/commpay-vpay-docker-np-loc/docker/base-images/dotnet/runtime:8.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              ls -lrt /etc/custom-ca/
              cp /etc/custom-ca/vpay-root-ca.crt /usr/local/share/ca-certificates
              update-ca-certificates
              cp -r /etc/ssl/certs/* /ca-store/
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/custom-ca
              name: vpay-custom-ca-generation
            - mountPath: /ca-store
              name: common-cert
      extraVolumes:
        - name: vpay-custom-ca-generation
          configMap:
            name: vpay-custom-ca-generation
            defaultMode: 420
        - name: common-cert
          emptyDir: {}
    charts:
      - api

global:
  parent: 'payment'
  environment:
    name: Development
    ingress:
      subdomain: dev.pks.vpayusa.net

api:
  enabled: true
  listeningPort: 8080           # <-- CHANGED from 80 to 8080
  contentRoot: /app
  probes:
    readiness:
      endpoint: /api/about
    liveness:
      endpoint: /api/about
  image:
    name: payment-api/payment-web-api
  secrets:
    appsettings.secure.json:
      data: {}
  resources:
    requests:
      memory: "256Mi"
      cpu: "10m"
    limits:
      memory: "512Mi"
      cpu: "100m"


      
