name: build-and-deploy-to-dev
on:
  workflow_dispatch:
    inputs:
      PRE:
        required: true
        type: boolean
        default: true
  release:
    types: [published]
  push:
    tags:
      - "*"

jobs:
  sonar:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/sonar-analysis.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
  build-and-publish:
    needs: sonar
    if: always()
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/docker-build-and-publish.yml@feat/jfrog-saas-migration
    with: 
      PROJECT: payment-api
      IMAGE_NAME: payment-web-api
      BUILD_ARGS: "PROJECT_DIR PROJECT_NAME"
      DOCKER_URL: "centraluhg.jfrog.io"
      DOCKER_USERNAME: 'devops_msa@optum.com'
      DOCKER_REGISTRY_URL: "centraluhg.jfrog.io/commpay-vpay-docker-vir/docker"
      BUILD_ARGS_ENV_FILE_PATH: .github/build-args/
      PRE: ${{ (inputs.PRE == true || github.event_name == 'push' ) && github.event_name != 'release' }}
    secrets: 
      DOCKER_PASSWORD: ${{ secrets.TEST_MSA_JFTK }} 
      
  deployment-plano-dev:
    #if: always()
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-dev.yml@feat/jfrog-saas-migration
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      RELEASE_NAME: payment-api
      DRYRUN: false
    secrets: inherit
  deployment-stl-dev:
    #if: always()
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-dev.yml@feat/jfrog-saas-migration
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      RELEASE_NAME: payment-api
      DRYRUN: false
    secrets: inherit    
