name: helm-build-and-deploy-to-dev
on: 
  workflow_dispatch:
  push:
    tags:
    - '*'
jobs:
  build-and-publish:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/docker-build-and-publish.yml@main
    with: 
      PROJECT: payment-api
      IMAGE_NAME: payment-web-api
      BUILD_ARGS: "PROJECT_DIR PROJECT_NAME"
      DOCKER_URL: ${{ vars.VPAY_DOCKER_REGISTRY_URL }}
      DOCKER_USERNAME: ${{ vars.VPAY_CI_REGISTRY_USER }}
      BUILD_ARGS_ENV_FILE_PATH: .github/build-args/
    secrets:
      DOCKER_PASSWORD: ${{ secrets.VPAY_CI_REGISTRY_PASSWORD }}
  deployment-plano-dev-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-dev.yml@main
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      VALUE_FILES_ENV: dev
      DEFAULT_VALUES_ENVIRONMENT_NAME: Development
      RELEASE_NAME: payment-api
      VALUE_FILES_DC: plano
      DATACENTER: Plano
      CONTEXT_NAME: pldev
      SECRET_REPLACE_ENV: dev
      VALUE_FILES_DC_DOMAIN: pl
      VAULT_URL: ${{ vars.VPAY_DEV_VAULT_URL }}
      DRYRUN: true
    secrets:
      VPAY_KUBECONFIG: ${{ secrets.VPAY_KUBECONFIG }}
      VAULT_TOKEN: ${{ secrets.DEVVAULT_TOKEN }}      
  deployment-stl-dev-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-dev.yml@main
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      VALUE_FILES_ENV: dev
      DEFAULT_VALUES_ENVIRONMENT_NAME: Development
      RELEASE_NAME: payment-api
      VALUE_FILES_DC: stl
      DATACENTER: St. Louis
      CONTEXT_NAME: stldev
      SECRET_REPLACE_ENV: dev
      VALUE_FILES_DC_DOMAIN: stl
      VAULT_URL: ${{ vars.VPAY_DEV_VAULT_URL }}
      DRYRUN: true
    secrets:
      VPAY_KUBECONFIG: ${{ secrets.VPAY_KUBECONFIG }}
      VAULT_TOKEN: ${{ secrets.DEVVAULT_TOKEN }}
  deployment-plano-stage-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-stage.yml@main
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-stage
      RELEASE_NAME: payment-api
      DRYRUN: true
    secrets: inherit
  deployment-stl-stage-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-stage.yml@main
    needs: build-and-publish    
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-stage
      RELEASE_NAME: payment-api
      DRYRUN: true
    secrets: inherit
  deployment-plano-prod-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-prod.yml@main
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-prod
      RELEASE_NAME: payment-api
      DRYRUN: true
    secrets: inherit      
  deployment-stl-prod-dryrun:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-prod.yml@main
    needs: build-and-publish
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-prod
      RELEASE_NAME: payment-api
      DRYRUN: true
    secrets: inherit      
  deployment-plano-dev:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-plano-dev.yml@main
    needs: [deployment-plano-dev-dryrun, deployment-stl-dev-dryrun]
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      RELEASE_NAME: payment-api
      DRYRUN: false
    secrets: inherit
  deployment-stl-dev:
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/helm-deploy-stl-dev.yml@main
    needs: [deployment-plano-dev-dryrun, deployment-stl-dev-dryrun]
    with: 
      CHARTS_PATH: charts/payment-api
      NAMESPACE: client-payments-dev
      RELEASE_NAME: payment-api
      DRYRUN: false
    secrets: inherit    
