name: SonarQube                      
on:
  workflow_call:     
  push:       
       
jobs:      
  check:
    name: Sonar
    uses: optum-financial/vpay-actions-common-workflow/.github/workflows/sonar-analysis.yml@sonar-scan-poc              
    secrets: inherit
  
